// Optional end-to-end regression checks. Requires Playwright and a running web build.
const {chromium}=require('playwright');const assert=require('node:assert/strict');
(async()=>{
const browser=await chromium.launch({executablePath:process.env.JARCADE_CHROME || undefined,headless:true,args:['--no-sandbox','--enable-unsafe-swiftshader','--disable-backgrounding-occluded-windows','--disable-background-timer-throttling']});
const ctx=await browser.newContext({viewport:{width:390,height:844},deviceScaleFactor:3,hasTouch:true,isMobile:true});const p=await ctx.newPage();const errors=[];p.on('pageerror',e=>errors.push(e.message));p.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
await p.addInitScript(()=>{const now=Date.now()/1000;localStorage.setItem('jarcade.fih.v1',`1 50 20 20 40 60 500 200 0 0 0 0 0 255 1 1 1 7 9 ${now} 0`);window.frames=0;const raf=requestAnimationFrame.bind(window);window.requestAnimationFrame=fn=>raf(t=>{frames++;fn(t);});});
const wait=t=>p.waitForFunction(t=>document.querySelector('#glcanvas').getAttribute('aria-label').includes(t),t);const tap=async(x,y)=>{await p.touchscreen.tap(x,y);await p.waitForTimeout(70);};const save=()=>p.evaluate(()=>localStorage.getItem('jarcade.fih.v1').split(' ').map(Number));
await p.goto(process.env.JARCADE_QA_URL || 'http://127.0.0.1:8080/');await wait('Select Snake');await tap(100,520);await wait('Fih. Kitchen');assert.equal(await p.evaluate(()=>document.querySelector('#glcanvas').width),1170);
await p.waitForTimeout(1700);let n=await p.evaluate(()=>frames);await p.waitForTimeout(200);assert(await p.evaluate(()=>frames)>n,'missing idle animation');
await tap(74,770);await tap(280,530);let before=await save();await tap(195,771);assert.equal((await save())[25],before[25],'tap consumed food');
const cd=await ctx.newCDPSession(p);const move=async(x,y)=>{await cd.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x,y,id:1}]});await p.waitForTimeout(18);};const start=async(x,y)=>{await cd.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x,y,id:1}]});await p.waitForTimeout(40);};const end=async()=>{await cd.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await p.waitForTimeout(100);};
await start(195,771);await move(265,427);await end();assert.equal((await save())[25],before[25],'body drop consumed food');
await start(195,771);for(let i=0;i<10;i++)await move(195,771-(771-447)*(i+1)/10);await p.screenshot({path:'/tmp/fih-food-gaze.png'});await end();let f=await save();assert.equal(f[25],before[25]-1);assert(Math.abs(f[1]-70)<1,'mouth drop failed');await p.screenshot({path:'/tmp/fih-chewing.png'});
await tap(350,144);await tap(195,445);assert.equal((await save())[10],0);assert.equal((await save())[6],500,'preview spent coins');await p.screenshot({path:'/tmp/fih-wardrobe-preview.png'});await tap(195,750);f=await save();assert.equal(f[10],1);assert.equal(f[6],470);await tap(195,750);assert.equal((await save())[6],470);await tap(344,96);
await tap(144,28);await wait('Fih. Bathroom');await tap(195,771);assert.equal((await save())[3],f[3],'rinse without rubbing cleaned fish');await start(73,771);await move(195,417);await end();await tap(195,771);assert.equal((await save())[3],f[3],'stationary soap cleaned fish');
await start(73,771);await move(250,417);for(let loop=0;loop<3;loop++)for(let i=0;i<48;i++){const a=i*Math.PI*2/48;await move(195+Math.cos(a)*55,417+Math.sin(a)*55);}await p.screenshot({path:'/tmp/fih-soap-rubbing.png'});await end();await tap(195,771);let washed=await save();assert(Math.abs(washed[3]-f[3]-35)<1,'rubbing then rinsing failed');await p.screenshot({path:'/tmp/fih-shower.png'});
await tap(247,28);await wait('Fih. Bedroom');await tap(74,771);assert.equal((await save())[8],1);await p.screenshot({path:'/tmp/fih-vector-sleep.png'});await tap(74,771);assert.equal((await save())[8],0);
await tap(195,28);await wait('Fih. Playroom');await tap(74,771);await p.screenshot({path:'/tmp/fih-vector-games.png'});
const cards=[[100,230,'Pearl Catch'],[280,230,'Bubble Pop'],[100,440,'Memory Reef'],[280,440,'Reef Hop'],[100,650,'Reef Dash']];
for(const [x,y,kind] of cards){await tap(x,y);await wait(`${kind}. Running`);if(kind==='Bubble Pop'){await p.keyboard.down('ArrowLeft');await p.keyboard.down('ArrowUp');await p.waitForTimeout(950);await p.keyboard.up('ArrowLeft');await p.keyboard.up('ArrowUp');await p.keyboard.press('Space');assert((await p.locator('#glcanvas').getAttribute('aria-label')).includes('Score 0.'),'Space auto aimed');}await p.waitForTimeout(180);await p.screenshot({path:`/tmp/fih-game-${kind.replaceAll(' ','-')}.png`});await tap(350,34);await wait(`${kind}. Paused`);n=await p.evaluate(()=>frames);await p.waitForTimeout(150);assert(await p.evaluate(()=>frames)<=n+1,'paused minigame redraws');await tap(34,34);}
assert.deepEqual(errors,[]);console.log('PASS: phone DPR3, idle animation, tap/body drop rejected, mouth feeding/gaze, clothing preview/purchase once, real rubbing, rinse, sleep and all five games.');await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
