const {chromium}=require('playwright');const assert=require('node:assert/strict');const {play,setup}=require('./sudoku-layout.cjs');
const base=process.env.JARCADE_QA_URL||'http://127.0.0.1:8092';
(async()=>{const browser=await chromium.launch({executablePath:process.env.JARCADE_CHROME||'/usr/bin/google-chrome',args:['--no-sandbox','--enable-unsafe-swiftshader']});const errors=[];
const cases=process.env.JARCADE_QA_FOCUS==='controls'?[[1440,900,false],[568,320,false],[390,844,true]]:[[390,844,false],[1440,900,false],[320,568,false],[568,320,false],[390,844,true]];
try{for(const[w,h,saver]of cases){
 const c=await browser.newContext({viewport:{width:w,height:h},deviceScaleFactor:3,hasTouch:true});await c.addInitScript(saver=>{localStorage.setItem('jarcade.settings.v1',`3 ${saver?1:0} 1 0 1`);const raf=requestAnimationFrame;window.__frames=0;window.requestAnimationFrame=cb=>raf.call(window,t=>{window.__frames++;cb(t);});},saver);
 const p=await c.newPage();p.on('pageerror',e=>errors.push(e.message));const ready=s=>p.waitForFunction(s=>document.querySelector('canvas')?.getAttribute('aria-label')?.includes(s),s,{timeout:30000});const raw=()=>p.evaluate(()=>localStorage.getItem('jarcade.sudoku.v1'));const game=async()=>JSON.parse(await raw()).game;const key=async k=>{await p.keyboard.press(k);await p.waitForTimeout(65);};const tap=async xy=>{await p.touchscreen.tap(...xy);await p.waitForTimeout(80);};
 await p.goto(`${base}/?game=sudoku`);await ready('Choose a variant');await p.screenshot({path:`/tmp/jarcade-sudoku-setup-${w}-${saver}.png`});
 const exhaustive=w===390&&!saver;const variants=exhaustive?[0,1,2,3,4,5]:[0,1];let saved=false;
 for(const variant of variants)for(const level of exhaustive?[0,1,2]:[1]){
   const s=setup(w,h,saved);await tap(s.variant(0));if(variant!==0)await tap(s.variant(variant));await tap(s.difficulty(level));await tap(s.new);await ready('Digit mode');saved=true;let g=await game();assert.equal(g.puzzle.variant,['Classic','Killer','Xv','Kropki','Thermo','Diagonal'][variant]);assert.equal(g.puzzle.difficulty,['Easy','Medium','Hard'][level]);
   assert.equal(g.puzzle.givens.length,81);assert.equal(g.puzzle.solution.length,81);assert(g.puzzle.givens.includes(0));if(variant===1)assert(g.puzzle.cages.length>0);if(variant===2||variant===3)assert(g.puzzle.edges.length>0);if(variant===4)assert(g.puzzle.thermos.length>0);
   if(level===2||!exhaustive)await p.screenshot({path:`/tmp/jarcade-sudoku-${w}-${saver}-${variant}.png`});
   await key('Escape');await ready('Choose a variant');
 }
 await tap(setup(w,h,true).resume);await ready('Digit mode');const l=play(w,h);let g=await game();const blanks=g.puzzle.givens.map((v,i)=>v===0?i:-1).filter(i=>i>=0),i=blanks[0],given=g.puzzle.givens.findIndex(v=>v>0);await tap(l.cell(i));
 await key('Shift+5');assert.equal((await game()).marks[i][1],16);await key('Control+z');assert.equal((await game()).marks[i][1],0);await key('Control+6');assert.equal((await game()).marks[i][2],32);await key('Control+z');assert.equal((await game()).marks[i][2],0);await key('Control+Shift+7');assert.equal((await game()).marks[i][3],7);await key('Control+z');assert.equal((await game()).marks[i][3],0);
 await key('Space');await ready('Corner notes mode');await tap(l.number(3));assert.equal((await game()).marks[i][1],4);await key('c');await ready('Centre notes mode');await tap(l.number(4));assert.equal((await game()).marks[i][2],8);await key('v');await ready('Colour mode');await tap(l.number(2));assert.equal((await game()).marks[i][3],2);await key('Space');await ready('Digit mode');
 const correct=g.puzzle.solution[i],wrong=correct%9+1;await tap(l.number(wrong));assert.equal((await game()).marks[i][0],wrong);await ready('incorrect digit');await key('k');await ready('incorrect digit');await key('h');await ready('contradicts');assert.equal((await game()).marks[i][0],wrong);await tap(l.erase);assert.equal((await game()).marks[i][0],0);await key('Control+z');assert.equal((await game()).marks[i][0],wrong);await key('Control+y');assert.equal((await game()).marks[i][0],0);await key('h');await p.waitForTimeout(80);assert.equal((await game()).hints,1);
 const beforeGiven=(await game()).marks[given];await tap(l.cell(given));await tap(l.number(9));assert.deepEqual((await game()).marks[given],beforeGiven);
 // Multi-cell notes apply as one undoable action, including fast drags.
 await key('x');await p.mouse.move(...l.cell(0));await p.mouse.down();await p.mouse.move(...l.cell(8),{steps:9});await p.mouse.up();await p.waitForTimeout(100);const beforeGroup=await raw();await key('8');const group=await game();assert(group.marks.some(m=>m[1]&128));await key('Control+z');assert.equal((await game()).marks.toString(),JSON.parse(beforeGroup).game.marks.toString());
 // Pinch changes geometry, never entries or history; then fit.
 const beforePinch=await raw();const client=await c.newCDPSession(p);const a=l.cell(20),b=l.cell(60);await client.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:a[0],y:a[1],id:1},{x:b[0],y:b[1],id:2}]});await p.waitForTimeout(65);await client.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:a[0]-15,y:a[1]-15,id:1},{x:b[0]+15,y:b[1]+15,id:2}]});await p.waitForTimeout(65);await client.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await p.waitForTimeout(80);assert.equal(await raw(),beforePinch);await tap(l.action(4));
 const stored=await raw();await p.reload();await ready('Choose a variant');await tap(setup(w,h,true).resume);await ready('Digit mode');assert.equal(await raw(),stored);
 await tap([w-30,30]);await ready('Rules.');await p.screenshot({path:`/tmp/jarcade-sudoku-help-${w}.png`});await key('Escape');await ready('Digit mode');
 // Full keyboard completion exercises winning and persistence on the main phone.
 if(exhaustive){g=await game();await key('r');await ready('Clear this puzzle?');const mw=Math.min(w-24,460),mx=(w-mw)/2;await tap([mx+20+(mw-50)/2+10+(mw-50)/4,(h-190)/2+152]);await ready('Digit mode');
   for(let j=0;j<81;j++)if(g.puzzle.givens[j]===0){await tap(l.cell(j));await key(String(g.puzzle.solution[j]));}await ready('Puzzle complete');assert((await game()).marks.every((m,j)=>g.puzzle.givens[j]||m[0]===g.puzzle.solution[j]));await p.screenshot({path:'/tmp/jarcade-sudoku-complete.png'});}
 await p.waitForTimeout(400);const frames=await p.evaluate(()=>window.__frames);await p.waitForTimeout(400);assert.equal(await p.evaluate(()=>window.__frames),frames,'Sudoku must not redraw while idle with FPS enabled');
 const dpi=await p.evaluate(()=>({w:document.querySelector('canvas').width,h:document.querySelector('canvas').height}));assert.equal(dpi.w,w*3);assert.equal(dpi.h,h*3);
 await key('Escape');await ready('Choose a variant');const beforeCancel=await raw();await tap(setup(w,h,true).variant(0));await tap(setup(w,h,true).variant(5));await tap(setup(w,h,true).difficulty(2));await p.touchscreen.tap(...setup(w,h,true).new);await ready('Generating Diagonal Hard');await key('Escape');await ready('Choose a variant');assert.equal(await raw(),beforeCancel,'Cancelling generation must preserve the saved puzzle');await key('Escape');await ready('Select Snake');await key('Tab');await p.waitForTimeout(100);assert((await p.locator('canvas').getAttribute('aria-label')).includes('Sudoku'));await c.close();console.log(`Sudoku passed: ${w}×${h}, ${saver?'black':'white'}`);
 }assert.deepEqual(errors,[]);console.log('All generated modes and difficulty selectors, notes/colours, immutable givens, check/hints, undo/redo, drag selection, pinch, reload, full win, high DPI and idle rendering passed.');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
